targetsetup accesskey
AnneTrue/libConglomerate pull request #26
Opened 2020-11-02 18:30 UTC by haliphax

2020-11-02 18:32 UTC, haliphax commented
Done force-pushing, I swear :rofl:

2020-11-02 18:41 UTC, AnneTrue requested changes
The access key R is already used by "retrieve item", I would recommend a different default access key.

2020-11-03 16:55 UTC, haliphax commented
Yeah, pretty sure I had even realized that and changed it in my local copy, but forgot to update what I was pushing.

2020-11-03 16:59 UTC, AnneTrue approved these changes

2020-11-03 17:00 UTC, merged